site_name: TheDeathlyCow

theme:
  name: material

  palette:
    - scheme: slate
      primary: custom
      features:
        - navigation.expand
  
  font:
    text: Lato

copyright: >
  © TheDeathlyCow. 
  <br/>
  All content on this website is licensed under <a href="https://github.com/TheDeathlyCow/thedeathlycow.github.io/blob/main/LICENSE"> CC-BY-NC-SA 4.0</a> unless otherwise noted.


extra_css:
  - assets/styles.css

markdown_extensions:
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

nav:
  - index.md
  - "Minecraft Mods":
    - frostiful.md
    - scorchful.md
    - immersive-storms.md